export enum SaleEventType {
  UPDATE_SALE,
  UPDATE_SALE_PRICE,
  ADD_ITEM_VARIANT,
  UPDATE_SALE_VARIANT,
  UPDATE_SALE_VARIANT_PRICE,
  REMOVE_SALE_VARIANT,
  ADD_SALE_PAYMENT,
  REMOVE_SALE_PAYMENT
}
