// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/stream-series/stream-series.d.ts
// Type definitions for stream-series
// Project: https://github.com/rschmukler/stream-series
// Definitions by: Keita Kagurazaka <https://github.com/k-kagurazaka>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "stream-series" {
    function series<T extends NodeJS.ReadableStream>(...streams: T[]): NodeJS.ReadWriteStream;
    export = series;
}