// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/extend/extend.d.ts
// Type definitions for extend v2.0.0
// Project: https://www.npmjs.com/package/extend
// Definitions by: Stefan Steinhart <https://github.com/reppners>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
declare module "extend" {

    function extend(deepOrObject:boolean | Object, ...objectN: Object[]): any;
    namespace extend {}
    export = extend;
}